version: "3.8"

services:
  jenkins:
    image: appium_jenkins
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appium_jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - appium_jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

volumes:
  appium_jenkins: